### PR TITLE
Fix Swift image

### PR DESCRIPTION
**Pull request by grahamburgsma**
Fixes the Swift image by actually basing it on the Swift docker image rather than just alpine.

Related to https://github.com/snyk/actions/pull/133.

### CODE REVIEW

**Comment by thisislawatts** [comment]
Thanks for raising the PR @grahamburgsma, lets see if we can get this sorted out :)

**Review by thisislawatts — APPROVED** [review]

**Comment by grahamburgsma** [comment]
Thanks @thisislawatts. Are you able to get https://github.com/snyk/actions/pull/133 merged as well? I've tested and it works now that this one is merged.

**Comment by thisislawatts** [comment]
Thanks for the follow up @grahamburgsma, I have not yet been able to verify the built image successfully tests a swift project. I would like to see this behaving correctly before updating the Actions repo. 

Heres the command I would expect to see test results with:

```bash
$ docker run --rm -it --env SNYK_TOKEN --env DEBUG -v $(pwd):/app snyk/snyk:swift
```

**Comment by grahamburgsma** [comment]
> I would like to see this behaving correctly before updating the Actions repo.

@thisislawatts If this helps, here is the test I ran yesterday using my actions fork. The action includes a bunch of other inputs, but you can see it runs against `snyk/snyk:swift`. 


Screenshot 2024-01-30 at 7 54 54 AM

**Comment by thisislawatts** [comment]
Thanks for confirming @grahamburgsma, great to see this working. I have not yet had a successful test run when working directly with the image, this manual QA blocks further usage of this image being rolled out. Be sure that merging your changes to the actions repo is top of my list once the QA is complete.

**Pull request merged**
