### PR TITLE
feat: add python 3.11

### PR DESCRIPTION
**Pull request by ndclt**
* add Python 3.11 to the targeted versions

### CODE REVIEW

**Comment by bobbywatson3** [comment]
This would be great. Can we get this in?

**Comment by nullfact0r** [comment]
Would be great if this gets merged as I currently can't use Snyk due to this

**Review by bastiandoetsch — APPROVED** [review]
Thanks for the contribution - I'll merge it in. For future contributions, please be aware that the build.yml change is not necessary - it is automatically generated.

**Comment by bastiandoetsch** [comment]
@ndclt would you please gpg sign your commit and force-push? I can't merge before the commit is signed.

**Comment by ndclt** [comment]
@bastiandoetsch thanks for your answer. Ok for signing the commit, I'll do it and ping you.

**Comment by ndclt** [comment]
@bastiandoetsch It's done. The commit is signed.

**Comment by bastiandoetsch** [comment]
Merged @ndclt :)

**Comment by nullfact0r** [comment]
🥳

**Pull request merged**
